import { useMemo, useRef, useState, type ReactNode } from "react";
import { Boxes, BrainCircuit, CarFront, ChevronLeft, ChevronRight, CircleHelp, Clock3, Compass, Crosshair, Dices, Flame, Gamepad2, Globe2, Heart, Joystick, LetterText, LogOut, Menu, MousePointer2, MousePointerClick, Palette, Play, Search, Shield, ShieldCheck, SlidersHorizontal, Sparkles, Spade, Star, Trophy, User, X, Zap } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import PortalSidebar from "@/components/PortalSidebar";
import AdBannerView from "@/components/AdBannerView";
import AdminAdSettings from "@/components/AdminAdSettings";
import type { AdBanner, AdSlot } from "../../../shared/ads";
import { categories, defaultGames, getPortalCoverUrl, matchesPortalQuickView, type CategoryKey, type Locale, type PortalGame, type PortalView } from "../../../shared/games";

type View = PortalView;
type User = { username: "admin" | "igrok"; role: "admin" | "player" };
const copy = {
  ru: { all: "Все игры", history: "История", favorites: "Избранное", new: "Новинки", hot: "Популярные игры", updated: "Обновлённые", originals: "Оригинальные игры", multiplayer: "Мультиплеер", leaderboards: "Таблица лидеров", categories: "Категории", search: "Найти игру или тег...", popular: "Популярные", newest: "Новые", rating: "По рейтингу", weekly: "ИГРА НЕДЕЛИ", hero1: "Скорость", hero2: "без границ", heroText: "Врывайтесь в Neon Drift — самые быстрые ночные гонки уже в браузере.", play: "Играть бесплатно", more: "Подробнее", trending: "Сейчас в тренде", scroll: "Листайте →", games: "Все игры", found: "игр", notFound: "Игры не найдены", notFoundHint: "Попробуйте другой запрос или категорию", ad: "Рекламное место", login: "Войти", logout: "Выйти", admin: "Админ-панель", signInTitle: "Войти в GameHaven", username: "Логин", password: "Пароль", signIn: "Войти", adminTitle: "Управление играми", gameLink: "Ссылка на HTML5-игру (iframe URL)", save: "Сохранить игру", saving: "Сохранение…", image: "Загрузить обложку", coverUrl: "Или вставьте URL обложки", imageHint: "JPG / PNG / WebP, до 5 МБ", imageUrlHint: "HTTPS-ссылка или путь /manus-storage/...", titleRu: "Название — русский", titleEn: "Название — English", titleZh: "Название — 中文", noFavorites: "В избранном пока пусто", noFavoritesHint: "Нажмите на сердечко в карточке игры, чтобы сохранить её.", notConnected: "Игра ещё не подключена", askAdmin: "Администратор добавит ссылку на игру.", controls: "Управление", about: "Об игре", plays: "игр", added: "Добавлено в избранное", removed: "Удалено из избранного", saved: "Изменения сохранены", badLogin: "Проверьте логин и пароль", iframeTip: "Если провайдер блокирует iframe, используйте его HTML5 embed-ссылку.", loadError: "Не удалось загрузить каталог", signInRequired: "Войдите как игрок, чтобы использовать избранное." },
  en: { all: "All games", history: "History", favorites: "Favorites", new: "New", hot: "Hot Games", updated: "Updated", originals: "Originals", multiplayer: "Multiplayer", leaderboards: "Leaderboards", categories: "Categories", search: "Search games or tags...", popular: "Popular", newest: "Newest", rating: "Top rated", weekly: "GAME OF THE WEEK", hero1: "Speed", hero2: "without limits", heroText: "Dive into Neon Drift — the fastest night races are right in your browser.", play: "Play for free", more: "Details", trending: "Trending now", scroll: "Scroll →", games: "All games", found: "games", notFound: "No games found", notFoundHint: "Try another search or category", ad: "Ad space", login: "Sign in", logout: "Sign out", admin: "Admin panel", signInTitle: "Sign in to GameHaven", username: "Username", password: "Password", signIn: "Sign in", adminTitle: "Manage games", gameLink: "HTML5 game link (iframe URL)", save: "Save game", saving: "Saving…", image: "Upload cover", coverUrl: "Or paste a cover URL", imageHint: "JPG / PNG / WebP, up to 5 MB", imageUrlHint: "HTTPS URL or /manus-storage/... path", titleRu: "Title — Русский", titleEn: "Title — English", titleZh: "Title — 中文", noFavorites: "Your favorites are empty", noFavoritesHint: "Tap the heart on a game card to save it here.", notConnected: "This game is not connected yet", askAdmin: "An administrator will add the game link.", controls: "Controls", about: "About", plays: "plays", added: "Added to favorites", removed: "Removed from favorites", saved: "Changes saved", badLogin: "Check your username and password", iframeTip: "If the provider blocks embedding, use its HTML5 embed URL.", loadError: "Could not load the catalog", signInRequired: "Sign in as a player to use favorites." },
  zh: { all: "全部游戏", history: "游玩记录", favorites: "收藏夹", new: "最新", hot: "热门游戏", updated: "最近更新", originals: "原创游戏", multiplayer: "多人游戏", leaderboards: "排行榜", categories: "游戏分类", search: "搜索游戏或标签...", popular: "热门", newest: "最新", rating: "高分", weekly: "本周游戏", hero1: "速度", hero2: "无极限", heroText: "进入 Neon Drift，体验就在浏览器中的极速夜间竞速。", play: "免费游玩", more: "详情", trending: "热门推荐", scroll: "滑动 →", games: "全部游戏", found: "款游戏", notFound: "没有找到游戏", notFoundHint: "试试其他关键词或分类", ad: "广告位", login: "登录", logout: "退出", admin: "管理面板", signInTitle: "登录 GameHaven", username: "账号", password: "密码", signIn: "登录", adminTitle: "管理游戏", gameLink: "HTML5 游戏链接（iframe URL）", save: "保存游戏", saving: "保存中…", image: "上传封面", coverUrl: "或粘贴封面 URL", imageHint: "JPG / PNG / WebP，最大 5 MB", imageUrlHint: "HTTPS 链接或 /manus-storage/... 路径", titleRu: "名称 — Русский", titleEn: "名称 — English", titleZh: "名称 — 中文", noFavorites: "还没有收藏游戏", noFavoritesHint: "点击游戏卡片上的心形图标即可收藏。", notConnected: "游戏尚未连接", askAdmin: "管理员将添加游戏链接。", controls: "操作方式", about: "游戏介绍", plays: "次游玩", added: "已添加到收藏", removed: "已从收藏移除", saved: "已保存更改", badLogin: "请检查账号和密码", iframeTip: "如果提供商禁止嵌入，请使用其 HTML5 embed 链接。", loadError: "无法加载游戏目录", signInRequired: "请以玩家身份登录后使用收藏。" },
} as const;
const categoryLabels: Record<Locale, Record<CategoryKey, string>> = {
  ru: { action: "Экшен", adventure: "Приключения", arcade: "Аркадные", board: "Настольные", card: "Карточные", clicker: "Кликеры", driving: "Гонки", io: ".io", puzzle: "Головоломки", shooting: "Стрелялки", simulation: "Симуляторы", sports: "Спорт", strategy: "Стратегии", trivia: "Викторины", word: "Слова" },
  en: { action: "Action", adventure: "Adventure", arcade: "Arcade", board: "Board", card: "Card", clicker: "Clicker", driving: "Driving", io: ".io", puzzle: "Puzzle", shooting: "Shooting", simulation: "Simulation", sports: "Sports", strategy: "Strategy", trivia: "Trivia", word: "Word" },
  zh: { action: "动作", adventure: "冒险", arcade: "街机", board: "桌游", card: "卡牌", clicker: "点击", driving: "驾驶", io: ".io", puzzle: "益智", shooting: "射击", simulation: "模拟", sports: "体育", strategy: "策略", trivia: "问答", word: "文字" },
};
const categoryIcons: Record<CategoryKey, typeof Zap> = {
  action: Zap, adventure: Compass, arcade: Joystick, board: Dices, card: Spade,
  clicker: MousePointerClick, driving: CarFront, io: Palette, puzzle: BrainCircuit,
  shooting: Crosshair, simulation: Boxes, sports: Trophy, strategy: Shield,
  trivia: CircleHelp, word: LetterText,
};
const localeLabels: Record<Locale, string> = { ru: "RU", en: "EN", zh: "中文" };
const fmtPlays = (n: number, locale: Locale) => new Intl.NumberFormat(locale === "zh" ? "zh-CN" : locale, { notation: "compact", maximumFractionDigits: 1 }).format(n);

function useLocale() {
  const [locale, setLocale] = useState<Locale>(() => { try { const saved = localStorage.getItem("gamehaven-locale"); if (saved === "en" || saved === "zh" || saved === "ru") return saved; } catch { /* storage disabled */ } return "ru"; });
  const change = (next: Locale) => { setLocale(next); try { localStorage.setItem("gamehaven-locale", next); } catch { /* ignore */ } };
  return [locale, change] as const;
}

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-3 backdrop-blur-sm" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><section role="dialog" aria-modal="true" aria-label={title} className="panel-glow max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-xl border border-border bg-[#0c1727] p-4 sm:p-6"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-black sm:text-xl">{title}</h2><button onClick={close} aria-label="Close" className="rounded p-2 text-muted-foreground hover:bg-secondary hover:text-foreground"><X className="size-5" /></button></div>{children}</section></div>;
}

function GameCard({ game, locale, favorite, canFavorite, onFavorite, onPlay, pending, wide = false }: { game: PortalGame; locale: Locale; favorite: boolean; canFavorite: boolean; onFavorite: () => void; onPlay: () => void; pending: boolean; wide?: boolean }) {
  const t = copy[locale];
  return <article className={`game-card group relative overflow-hidden rounded-lg border border-border bg-card transition duration-300 hover:-translate-y-1 hover:border-primary/60 ${wide ? "min-w-[260px] sm:min-w-[320px]" : ""}`}>
    <button type="button" onClick={onPlay} className="block w-full text-left" aria-label={`${t.play}: ${game.titles[locale]}`}><div className="relative aspect-[16/10] overflow-hidden"><img src={getPortalCoverUrl(game)} alt={game.titles[locale]} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="cover-shade absolute inset-0 opacity-80 transition group-hover:opacity-95" />{game.badge && <span className={`absolute left-3 top-3 rounded px-2 py-1 text-[10px] font-black ${game.badge === "new" ? "bg-cyan-400 text-slate-950" : "bg-primary text-primary-foreground"}`}>{game.badge === "new" ? "NEW" : game.badge === "top" ? "TOP" : "HIT"}</span>}<span className="absolute inset-0 grid place-items-center opacity-0 transition group-hover:opacity-100"><span className="grid size-12 place-items-center rounded-full bg-primary text-primary-foreground shadow-[0_0_32px_rgba(183,255,66,.35)]"><Play className="ml-0.5 size-5 fill-current" /></span></span></div><div className="p-3"><div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-2"><div className="min-w-0"><h3 className="truncate font-bold text-card-foreground">{game.titles[locale]}</h3><p className="mt-1 text-xs text-muted-foreground">{categoryLabels[locale][game.category]} · {fmtPlays(game.plays, locale)} {t.plays}</p></div><span className="flex items-center gap-1 text-xs font-bold text-amber-300"><Star className="size-3 fill-current" />{game.rating}</span></div></div></button>
    {canFavorite && <button type="button" onClick={onFavorite} disabled={pending} aria-pressed={favorite} className={`absolute right-2 top-2 grid size-9 place-items-center rounded-md bg-slate-950/65 text-white backdrop-blur hover:bg-slate-950 disabled:cursor-wait disabled:opacity-60 ${favorite ? "text-pink-400" : ""}`} aria-label={favorite ? t.removed : t.added}><Heart className={`size-4 ${favorite ? "fill-current" : ""}`} /></button>}
  </article>;
}

function LoginDialog({ locale, close, success }: { locale: Locale; close: () => void; success: (user: User) => void }) {
  const t = copy[locale]; const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const login = trpc.portal.login.useMutation({ onSuccess: user => { success(user); close(); }, onError: () => setError(t.badLogin) });
  return <Modal title={t.signInTitle} close={close}><form className="mx-auto grid max-w-md gap-4" onSubmit={e => { e.preventDefault(); setError(""); login.mutate({ username, password }); }}><label className="grid gap-2 text-sm text-muted-foreground">{t.username}<input autoComplete="username" value={username} onChange={e => setUsername(e.target.value)} className="rounded-md border border-border bg-secondary px-3 py-3 text-foreground outline-none focus:border-primary" required /></label><label className="grid gap-2 text-sm text-muted-foreground">{t.password}<input type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} className="rounded-md border border-border bg-secondary px-3 py-3 text-foreground outline-none focus:border-primary" required /></label>{error && <p role="alert" className="text-sm text-red-400">{error}</p>}<button disabled={login.isPending} className="rounded-md bg-primary px-4 py-3 font-black text-primary-foreground disabled:opacity-60">{login.isPending ? "…" : t.signIn}</button></form></Modal>;
}

function AdminPanel({ games, banners, locale, saved, close }: { games: PortalGame[]; banners?: Partial<Record<AdSlot, AdBanner>>; locale: Locale; saved: () => void; close: () => void }) {
  const t = copy[locale];
  return <Modal title={t.adminTitle} close={close}><AdminAdSettings banners={banners} locale={locale} onSaved={saved} /><div className="grid gap-4 md:grid-cols-2">{games.map(game => <AdminGameForm key={game.slug} game={game} locale={locale} saved={saved} />)}</div></Modal>;
}

function AdminGameForm({ game, locale, saved }: { game: PortalGame; locale: Locale; saved: () => void }) {
  const t = copy[locale]; const [ru, setRu] = useState(game.titles.ru); const [en, setEn] = useState(game.titles.en); const [zh, setZh] = useState(game.titles.zh); const [url, setUrl] = useState(game.gameUrl ?? ""); const [imageData, setImageData] = useState(""); const [coverUrl, setCoverUrl] = useState(game.imageUrl); const [preview, setPreview] = useState(game.imageUrl);
  const update = trpc.portal.updateGame.useMutation({ onSuccess: result => { toast.success(t.saved); setImageData(""); setCoverUrl(result.imageUrl); setPreview(result.imageUrl); saved(); }, onError: e => toast.error(e.message) });
  const pick = (file?: File) => { if (!file) return; if (!/^image\/(jpeg|png|webp)$/.test(file.type) || file.size > 5 * 1024 * 1024) { toast.error(t.imageHint); return; } const reader = new FileReader(); reader.onload = () => { const result = String(reader.result ?? ""); setImageData(result); setPreview(result); }; reader.readAsDataURL(file); };
  const titleFields: [string, string, (value: string) => void][] = [[t.titleRu, ru, setRu], [t.titleEn, en, setEn], [t.titleZh, zh, setZh]];
  return <form className="overflow-hidden rounded-lg border border-border bg-card" onSubmit={e => { e.preventDefault(); update.mutate({ slug: game.slug, titles: { ru, en, zh }, gameUrl: url, imageUrl: coverUrl, imageData: imageData || undefined }); }}><div className="relative aspect-[16/9] overflow-hidden"><img src={preview} alt="" className="h-full w-full object-cover" /><div className="cover-shade absolute inset-0" /><span className="absolute bottom-3 left-3 font-bold">{game.titles[locale]}</span></div><div className="grid gap-3 p-4">{titleFields.map(([label, value, setter]) => <label key={label} className="grid gap-1 text-xs text-muted-foreground">{label}<input value={value} onChange={e => setter(e.target.value)} required className="rounded border border-border bg-secondary px-3 py-2 text-sm text-foreground outline-none focus:border-primary" /></label>)}<label className="grid gap-1 text-xs text-muted-foreground">{t.gameLink}<input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://games.example.com/embed/game" className="rounded border border-border bg-secondary px-3 py-2 text-sm text-foreground outline-none focus:border-primary" /><span className="text-[11px]">{t.iframeTip}</span></label><label className="grid gap-2 text-xs text-muted-foreground">{t.image}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e => pick(e.target.files?.[0])} className="block w-full text-xs file:mr-3 file:rounded file:border-0 file:bg-secondary file:px-3 file:py-2 file:text-foreground" /><span>{t.imageHint}</span></label><label className="grid gap-1 text-xs text-muted-foreground">{t.coverUrl}<input type="text" value={coverUrl} onChange={e => { setCoverUrl(e.target.value); setImageData(""); setPreview(e.target.value); }} placeholder="https://cdn.example.com/game-cover.jpg" className="rounded border border-border bg-secondary px-3 py-2 text-sm text-foreground outline-none focus:border-primary" /><span>{t.imageUrlHint}</span></label><button type="submit" disabled={update.isPending} className="rounded-md bg-primary px-4 py-2.5 text-sm font-black text-primary-foreground disabled:opacity-60">{update.isPending ? t.saving : t.save}</button></div></form>;
}

function GameDialog({ game, locale, close, favorite, canFavorite, onFavorite, favoritePending, played }: { game: PortalGame; locale: Locale; close: () => void; favorite: boolean; canFavorite: boolean; onFavorite: () => void; favoritePending: boolean; played: () => void }) {
  const t = copy[locale]; const frame = useRef<HTMLDivElement>(null);
  return <Modal title={game.titles[locale]} close={close}><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_260px]"><div><div ref={frame} className="relative aspect-video overflow-hidden rounded-lg border border-border bg-[#060d17]">{game.gameUrl ? <iframe title={game.titles[locale]} src={game.gameUrl} className="absolute inset-0 h-full w-full border-0" allow="autoplay; fullscreen; gamepad; pointer-lock" allowFullScreen referrerPolicy="no-referrer" onLoad={played} /> : <div className="absolute inset-0 grid place-items-center bg-cover bg-center" style={{ backgroundImage: `linear-gradient(#07101bbb,#07101bdd),url(${getPortalCoverUrl(game)})` }}><div className="max-w-sm px-6 text-center"><div className="mx-auto grid size-16 place-items-center rounded-full border border-primary/30 bg-primary/10 text-primary"><Gamepad2 className="size-8" /></div><p className="mt-4 font-bold">{t.notConnected}</p><p className="mt-2 text-sm text-muted-foreground">{t.askAdmin}</p></div></div>}</div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-sm text-muted-foreground">{fmtPlays(game.plays, locale)} {t.plays} · ★ {game.rating}</span><div className="flex gap-2"><button onClick={() => frame.current?.requestFullscreen?.()} className="rounded-md border border-border bg-secondary px-3 py-2 text-sm">⛶ Fullscreen</button>{canFavorite && <button disabled={favoritePending} aria-pressed={favorite} onClick={onFavorite} className={`flex items-center gap-2 rounded-md border border-border bg-secondary px-3 py-2 text-sm disabled:opacity-60 ${favorite ? "text-pink-400" : ""}`}><Heart className={`size-4 ${favorite ? "fill-current" : ""}`} />{favorite ? t.removed : t.added}</button>}</div></div><section className="mt-5"><h3 className="font-black">{t.about}</h3><p className="mt-2 leading-7 text-muted-foreground">{game.descriptions[locale]}</p><div className="mt-3 flex flex-wrap gap-2">{game.tags.map(tag => <span key={tag} className="rounded bg-secondary px-2.5 py-1 text-xs text-muted-foreground">#{tag}</span>)}</div></section></div><aside><div className="mb-3 flex items-center gap-2 text-sm font-black"><MousePointer2 className="size-4 text-primary" />{t.controls}</div><div className="space-y-2">{game.controls[locale].map(item => <div key={item} className="rounded-md border border-border bg-secondary/60 px-3 py-2.5 text-sm">{item}</div>)}</div></aside></div></Modal>;
}

export default function Home() {
  const [locale, setLocale] = useLocale(); const t = copy[locale];
  const [category, setCategory] = useState<CategoryKey | "all">("all"); const [view, setView] = useState<View>("all"); const [query, setQuery] = useState(""); const [sort, setSort] = useState<"popular" | "newest" | "rating">("popular"); const [collapsed, setCollapsed] = useState(false); const [mobileMenu, setMobileMenu] = useState(false); const [loginOpen, setLoginOpen] = useState(false); const [adminOpen, setAdminOpen] = useState(false); const [activeGame, setActiveGame] = useState<PortalGame | null>(null);
  const [history, setHistory] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("gamehaven-history") ?? "[]"); } catch { return []; } });
  const utils = trpc.useUtils(); const meQuery = trpc.portal.me.useQuery(); const user = (meQuery.data as User | null | undefined) ?? null; const gamesQuery = trpc.portal.games.useQuery(); const adBannersQuery = trpc.portal.adBanners.useQuery(); const isPlayer = user?.role === "player"; const favoritesQuery = trpc.portal.myFavorites.useQuery(undefined, { enabled: isPlayer }); const favorites = favoritesQuery.data ?? [];
  const loginMutation = trpc.portal.login.useMutation({ onSuccess: async account => { await meQuery.refetch(); if (account.role === "player") await favoritesQuery.refetch(); toast.success(account.role === "admin" ? t.admin : account.username); }, onError: () => toast.error(t.badLogin) });
  const logoutMutation = trpc.portal.logout.useMutation({ onSuccess: async () => { await meQuery.refetch(); await favoritesQuery.refetch(); setView("all"); toast.success(t.logout); } });
  const toggleFavorite = trpc.portal.setFavorite.useMutation({ onSuccess: async (_result, input) => { await favoritesQuery.refetch(); toast.success(input.favorite ? t.added : t.removed); }, onError: error => { if (error.data?.code === "UNAUTHORIZED") { setLoginOpen(true); toast.error(t.signInRequired); } else toast.error(error.message); } });
  const games = (gamesQuery.data as PortalGame[] | undefined) ?? defaultGames;
  const orderedGames = useMemo(() => [...games].sort((a, b) => view === "leaderboards" || sort === "popular" ? b.plays - a.plays : sort === "newest" ? b.year - a.year : b.rating - a.rating), [games, sort, view]);
  const hotSlugs = useMemo(() => new Set([...games].sort((a, b) => b.plays - a.plays).slice(0, 5).map(game => game.slug)), [games]);
  const filtered = useMemo(() => orderedGames.filter(game =>
    (category === "all" || game.category === category) &&
    (view !== "history" || history.includes(game.slug)) &&
    (view !== "favorites" || favorites.includes(game.slug)) &&
    matchesPortalQuickView(game, view, hotSlugs) &&
    `${game.titles.ru} ${game.titles.en} ${game.titles.zh} ${game.tags.join(" ")}`.toLocaleLowerCase(locale).includes(query.toLocaleLowerCase(locale))
  ), [orderedGames, category, view, history, favorites, hotSlugs, query, locale]);
  const hero = games[0];
  const addHistory = (slug: string) => { const next = [slug, ...history.filter(item => item !== slug)].slice(0, 12); setHistory(next); try { localStorage.setItem("gamehaven-history", JSON.stringify(next)); } catch { /* ignore */ } };
  const goView = (next: View) => { setView(next); setCategory("all"); setMobileMenu(false); };
  const favoriteGame = (slug: string) => { if (!isPlayer) { setLoginOpen(true); toast.info(t.signInRequired); return; } toggleFavorite.mutate({ slug, favorite: !favorites.includes(slug) }); };
  const startGame = (game: PortalGame) => { setActiveGame(game); addHistory(game.slug); };
  const sidebar = <PortalSidebar
    collapsed={collapsed}
    labels={t}
    categoryLabels={categoryLabels[locale]}
    categoryIcons={categoryIcons}
    categories={categories}
    games={games}
    view={view}
    category={category}
    isPlayer={isPlayer}
    sidebarBanner={adBannersQuery.data?.sidebar}
    onView={goView}
    onCategory={key => { setCategory(key); setView("all"); setMobileMenu(false); }}
  />;

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-40 hidden overflow-y-auto border-r border-sidebar-border bg-sidebar p-4 transition-[width] lg:block ${collapsed ? "w-20" : "w-64"}`}>{sidebar}<button type="button" onClick={() => setCollapsed(v => !v)} className="absolute -right-3 top-20 grid size-7 place-items-center rounded-full border border-border bg-secondary text-muted-foreground shadow" aria-label="Collapse sidebar">{collapsed ? <ChevronRight className="size-4" /> : <ChevronLeft className="size-4" />}</button></aside>
    <main className={`transition-[padding] ${collapsed ? "lg:pl-20" : "lg:pl-64"}`}><header className="glass sticky top-0 z-30 border-b border-border px-3 py-3 sm:px-5"><div className="mx-auto grid max-w-[1500px] grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2 sm:gap-3"><button onClick={() => setMobileMenu(v => !v)} className="grid size-10 place-items-center rounded-md border border-border bg-secondary lg:hidden" aria-label="Open menu"><Menu className="size-5" /></button><div className="relative min-w-0"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={t.search} className="h-10 w-full rounded-md border border-border bg-secondary pl-10 pr-9 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20" />{query && <button onClick={() => setQuery("")} className="absolute right-1 top-1 grid size-8 place-items-center rounded text-muted-foreground hover:text-foreground" aria-label="Clear search"><X className="size-4" /></button>}</div><div className="flex items-center gap-2"><label className="flex h-10 items-center gap-1.5 rounded-md border border-border bg-secondary px-2" title="Language"><Globe2 className="size-4 text-muted-foreground" /><select value={locale} onChange={e => setLocale(e.target.value as Locale)} className="max-w-[72px] bg-transparent text-xs font-bold outline-none">{(["ru", "en", "zh"] as Locale[]).map(v => <option key={v} value={v} className="bg-card">{localeLabels[v]}</option>)}</select></label>{user ? <div className="flex items-center gap-1">{user.role === "admin" ? <button onClick={() => setAdminOpen(true)} className="hidden h-10 items-center gap-2 rounded-md border border-primary/30 bg-primary/10 px-3 text-sm font-bold text-primary sm:flex"><ShieldCheck className="size-4" />{t.admin}</button> : <span className="hidden text-sm text-muted-foreground sm:inline">{user.username}</span>}<button onClick={() => logoutMutation.mutate()} className="grid size-10 place-items-center rounded-md border border-border bg-secondary text-muted-foreground hover:text-foreground" title={t.logout}><LogOut className="size-4" /></button></div> : <button onClick={() => setLoginOpen(true)} className="flex h-10 items-center gap-2 rounded-md bg-primary px-3 text-sm font-black text-primary-foreground"><User className="size-4" /><span className="hidden sm:inline">{t.login}</span></button>}</div></div>{mobileMenu && <div className="mt-3 max-h-[calc(100dvh-6rem)] overflow-y-auto rounded-lg border border-border bg-sidebar p-4 lg:hidden">{sidebar}</div>}</header>
      <div className="mx-auto max-w-[1500px] px-3 py-5 sm:px-5 lg:px-6"><div className="mx-auto mb-5 w-full max-w-[728px]"><AdBannerView banner={adBannersQuery.data?.leaderboard} label={t.ad} dimensions="728 × 90" className="aspect-[728/90] w-full" /></div>
        {view === "all" && category === "all" && !query && hero && <section className="relative mt-4 min-h-[350px] overflow-hidden rounded-lg border border-border bg-[#0b1220] sm:min-h-[390px]"><img src={hero.imageUrl} alt="" className="absolute inset-0 h-full w-full object-cover object-center" /><div className="hero-shade absolute inset-0" /><div className="relative flex min-h-[350px] max-w-xl flex-col justify-end p-6 sm:min-h-[390px] sm:p-9"><span className="mb-3 w-fit rounded bg-primary px-2 py-1 text-[10px] font-black tracking-[.12em] text-primary-foreground">{t.weekly}</span><h1 className="text-glow text-4xl font-black leading-tight sm:text-6xl">{t.hero1}<br /><span className="text-primary">{t.hero2}</span></h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-200 sm:text-base">{t.heroText}</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => startGame(hero)} className="flex h-11 items-center gap-2 rounded-md bg-primary px-5 text-sm font-black text-primary-foreground"><Play className="size-4 fill-current" />{t.play}</button><button onClick={() => startGame(hero)} className="h-11 rounded-md border border-white/20 bg-white/10 px-5 text-sm font-bold backdrop-blur hover:bg-white/15">{t.more}</button></div></div></section>}
        {view === "all" && category === "all" && !query && <section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 text-xl font-black"><Flame className="size-5 text-orange-400" />{t.trending}</h2><span className="text-xs text-muted-foreground">{t.scroll}</span></div><div className="no-scrollbar flex gap-4 overflow-x-auto pb-3">{games.slice(0, 5).map(game => <GameCard key={game.slug} game={game} locale={locale} favorite={favorites.includes(game.slug)} canFavorite={isPlayer} onFavorite={() => favoriteGame(game.slug)} onPlay={() => startGame(game)} pending={toggleFavorite.isPending} wide />)}</div></section>}
        <section className="mt-8"><div className="mb-4 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3"><div className="min-w-0"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-primary">{category === "all" ? view === "all" ? t.all : t[view] : categoryLabels[locale][category]}</p><h2 className="truncate text-2xl font-black">{query ? `${t.search.replace("...", "")}: “${query}”` : category === "all" ? view === "all" ? t.games : t[view] : categoryLabels[locale][category]}</h2></div><div className="flex items-center gap-2"><span className="hidden text-sm text-muted-foreground sm:inline">{filtered.length} {t.found}</span>{view !== "leaderboards" && (<label className="flex h-9 items-center gap-2 rounded-md border border-border bg-secondary px-2.5 text-xs"><SlidersHorizontal className="size-3.5 text-muted-foreground" /><select value={sort} onChange={e => setSort(e.target.value as typeof sort)} className="bg-transparent outline-none"><option value="popular">{t.popular}</option><option value="newest">{t.newest}</option><option value="rating">{t.rating}</option></select></label>)}</div></div>{filtered.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{filtered.map(game => <GameCard key={game.slug} game={game} locale={locale} favorite={favorites.includes(game.slug)} canFavorite={isPlayer} onFavorite={() => favoriteGame(game.slug)} onPlay={() => startGame(game)} pending={toggleFavorite.isPending} />)}</div> : <div className="grid min-h-56 place-items-center rounded-lg border border-dashed border-border text-center"><div>{view === "favorites" ? <Heart className="mx-auto size-8 text-muted-foreground" /> : <Gamepad2 className="mx-auto size-8 text-muted-foreground" />}<p className="mt-3 font-bold">{view === "favorites" ? t.noFavorites : t.notFound}</p><p className="mt-2 text-sm text-muted-foreground">{view === "favorites" ? t.noFavoritesHint : t.notFoundHint}</p></div></div>}</section>
        <footer className="mt-10 border-t border-border py-5 text-center text-xs text-muted-foreground">GAME<span className="font-black text-primary">HAVEN</span> · HTML5 ARCADE</footer>
      </div>
    </main>
    {mobileMenu && <div className="fixed inset-0 z-20 bg-black/35 lg:hidden" onClick={() => setMobileMenu(false)} />}
    {loginOpen && <LoginDialog locale={locale} close={() => setLoginOpen(false)} success={async account => { await meQuery.refetch(); if (account.role === "player") await favoritesQuery.refetch(); toast.success(account.role === "admin" ? t.admin : account.username); }} />}
    {adminOpen && user?.role === "admin" && <AdminPanel games={games} banners={adBannersQuery.data} locale={locale} close={() => setAdminOpen(false)} saved={() => { void utils.portal.games.invalidate(); void utils.portal.adBanners.invalidate(); }} />}
    {activeGame && <GameDialog game={activeGame} locale={locale} close={() => setActiveGame(null)} favorite={favorites.includes(activeGame.slug)} canFavorite={isPlayer} onFavorite={() => favoriteGame(activeGame.slug)} favoritePending={toggleFavorite.isPending} played={() => addHistory(activeGame.slug)} />}
    {gamesQuery.isLoading && <div className="fixed bottom-4 right-4 rounded-md border border-border bg-card px-3 py-2 text-xs text-muted-foreground">Loading…</div>}{gamesQuery.isError && <div role="alert" className="fixed bottom-4 right-4 rounded-md border border-red-500/30 bg-card px-3 py-2 text-xs text-red-300">{t.loadError}</div>}
  </div>;
}
